services:
  - type: web
    name: sistema-notas-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://mejiabran040504:GKfKFXs53TNRXMXj@alumnos.m7b201h.mongodb.net/?retryWrites=true&w=majority&appName=Alumnos
